import { z } from 'zod';

/**
 * Live-Scored Skies — aerial cinematography with original scoring.
 *
 * This is a LINE OF BUSINESS, not a founder's side interest, which is why it
 * gets its own collection at /skies rather than a shelf inside /portfolio
 * ("Design Portfolio" = client websites; filing aerial work there mis-frames it).
 *
 * The thesis of the whole collection is the `map` pairing below: each finished
 * film shown NEXT TO THE FLIGHT PATH THAT PRODUCED IT. Nobody else can show
 * that, because nobody else has the telemetry sitting under the footage. A film
 * with no map still renders — honestly, as a film — but the pairing is the point.
 *
 * Source of truth for the underlying catalogue is TOM's sky_library. This schema
 * is the CONTRACT that data must satisfy to reach the site. It is deliberately
 * NOT a live database read: lastapple.com is statically prerendered and runs on
 * content-as-code, so a row arrives here as MDX committed to git and is validated
 * at build time. A bad row fails `npm run build` instead of reaching a prospect.
 */

// Matches the ImageSchema used by the stream/service/solution collections.
const ImageSchema = z.object({
  src: z.string(),
  alt: z.string(),
  width: z.number().optional(),
  height: z.number().optional(),
});

/**
 * A number shown on the page must carry its own population and an as-of moment.
 *
 * Not pedantry. On 2026-08-02 every gate this site had proved a thing EXISTED
 * rather than that it WORKED, and analytics had been dead for seven months
 * behind green checks. A stat tile with no scope is the same failure shape: it
 * looks true, ages into a lie, and nobody notices.
 *
 * `scope` carries more weight than it first appears. On 2026-08-26 the 2026
 * cross-country map read 344 clips / 201 video / 121.9 GB while the catalogue
 * read 346 / 203 / 122.1, and this was diagnosed as the map being stale. It was
 * not. Two of the 346 rows carry no GPS and are both videos totalling 0.25 GB,
 * so the map — which counts only what it can PLOT — was exactly right, and so
 * was the catalogue, which counts every row. 346 - 2 = 344 reconciles the whole
 * gap. Neither number was wrong and nothing was stale; the population was
 * simply never declared. That is the failure this gate exists to catch.
 *
 * `value` accepts a number as well as a string on purpose: these arrive
 * generated by SQL, and every numeric error in this project's history came from
 * a human retyping a rendered figure. Do not force a cast that invites retyping.
 */
export const StatSchema = z.object({
  label: z.string(),
  value: z.union([z.string(), z.number()]),
  scope: z.string(),
  // Full ISO-8601 timestamp, not a bare date — see MapPublicationSchema.mediaAsOf.
  asOf: z.string().datetime({ offset: true }),
});

/**
 * A published interactive artifact hosted on its own Vercel project — the
 * cross-country trip maps and the 360 aerial spheres.
 *
 * These are EMBEDDED, not rebuilt. The live map (dark satellite basemap, points
 * clustered and coloured by the light they were shot in, live filters) is better
 * than anything this repo would draw, and it already ships. Verified 2026-08-25:
 * both apps return 200 and send neither X-Frame-Options nor a CSP
 * frame-ancestors directive, so they are embeddable as-is.
 *
 * `poster` is required because the embed is click-to-load: the still renders,
 * and the iframe is only created when a visitor asks for it. Four live iframes
 * on one page would wreck the phone, and mobile is the stated done-criterion.
 */
export const EmbedSchema = z.object({
  url: z.string().url(),
  poster: ImageSchema,
  // Optional: the sky_library.map_publications slug this embed came from, kept
  // so a snapshot can be reconciled against the catalogue it was exported from.
  publicationSlug: z.string().optional(),
});

export const SkiesEntrySchema = z.object({
  title: z.string().min(5),
  description: z.string().max(160),
  slug: z.string(),

  /**
   * Three artifact types share one collection so that publishing the next map
   * or sphere is a content commit rather than a code change.
   *   film — a scored film on the Hank Groman Music channel
   *   map  — a published trip map (flight telemetry)
   *   pano — an interactive 360 aerial sphere
   */
  kind: z.enum(['film', 'map', 'pano']),

  /**
   * One of the five CREATIVE vectors. Gives the collection its spine and lets
   * /skies group by intent rather than by chronology.
   *
   * DO NOT "reconcile" this list with sky_library.projects.vector. That column
   * has a CHECK constraint on an entirely different vocabulary — trip-story |
   * fcp-mastery | logic-mastery | gear | software | other — which describes the
   * PRODUCTION workstream, not the artistic intent. Two taxonomies wearing the
   * same name (found 2026-08-26). The creative vector rides in that table's
   * meta.creative_vector; read it from there, never from the column.
   *
   * Optional, and left UNSET on purpose until Hank confirms each film's vector.
   * A defensible default guessed by a machine is still a guess, and this label
   * is a claim about what the artist meant.
   */
  vector: z.enum([
    'field-to-frame',
    'drone-psalms',
    'midnight-compositions',
    'composer-in-the-wild',
    'echoes-of-the-journey',
  ]).optional(),

  // ── Film fields ──────────────────────────────────────────────────────────
  // The bare 11-character YouTube id, NOT a URL — the embed is constructed
  // here so every film gets the same click-to-load facade treatment.
  youtubeId: z.string().length(11).optional(),
  // Poster frames are committed to public/images/skies/ rather than hotlinked
  // from i.ytimg.com: no images.remotePatterns is configured, and the flagship
  // page should not put a third-party request on its critical path.
  poster: ImageSchema.optional(),
  durationSec: z.number().optional(),
  // Half of the product name is the scoring. Say which instrument.
  instrument: z.string().optional(),

  // ── Provenance ───────────────────────────────────────────────────────────
  // The trip that PRODUCED this work, as a sky_library trip slug.
  sourceTrip: z.string().optional(),
  locationName: z.string().optional(),
  state: z.string().optional(),
  filmedOn: z.string().optional(),

  /**
   * THE PAIRING — the map of the trip this was scored from.
   *
   * Optional on purpose, and null is the honest value when the map of a film's
   * source trip has not been published yet. Render "map in production"; never
   * pair a film with a map of a different trip to fill the slot.
   */
  map: EmbedSchema.optional(),

  // ── Map / pano entries ───────────────────────────────────────────────────
  // For kind 'map' and 'pano', the artifact itself.
  embed: EmbedSchema.optional(),

  // ── Presentation ─────────────────────────────────────────────────────────
  // Quote stats from the artifact a visitor can click through and check. A
  // number on the page that disagrees with the map it links to is worse than
  // no number at all.
  stats: z.array(StatSchema).optional(),
  releaseDate: z.string(),
  featured: z.boolean().default(false),
  published: z.boolean().default(true),
  order: z.number().default(0),
  body: z.string(),
})
  /**
   * A film without its video is not publishable — it would render as an empty
   * frame in front of a prospect. Fail the build instead.
   */
  .refine(
    (entry) => entry.kind !== 'film' || Boolean(entry.youtubeId),
    { message: 'A film entry requires a youtubeId', path: ['youtubeId'] }
  )
  /**
   * Likewise a map or sphere with nothing to embed. These carry the artifact in
   * `embed`; `map` is reserved for the film-beside-its-flight-path pairing.
   */
  .refine(
    (entry) => entry.kind === 'film' || Boolean(entry.embed),
    { message: 'A map or pano entry requires an embed', path: ['embed'] }
  );

/**
 * THE BUILD-TIME SNAPSHOT — content/skies/map-publications.json
 *
 * An export of sky_library.map_publications, committed to git and validated
 * here. This is deliberately NOT a runtime database read: lastapple.com is
 * statically prerendered, and a live query would put the flagship page's uptime
 * on Supabase and let a bad row render instead of failing loudly. A commit is
 * the refresh mechanism — which is the Red Light Test the site is built on.
 *
 * `mediaAsOf` is the load-bearing field. The published maps are STATIC
 * SNAPSHOTS: the 2026 cross-country map was published 2026-06-26 and by
 * 2026-08-26 the catalogue underneath it had 41 updated rows, so the map read
 * 201 videos / 121.9 GB while the database read 203 / 122.1. Recording when a
 * map last computed its own numbers is what makes that drift visible instead of
 * silently shipping a page whose stat tiles disagree with the map one click
 * away.
 */
export const MapPublicationSchema = z.object({
  slug: z.string(),
  title: z.string(),
  // The sky_library trip slug this map plots — the join that makes the
  // film-beside-its-flight-path pairing resolve.
  tripSlug: z.string(),
  url: z.string().url(),
  poster: ImageSchema,
  // Only published maps reach the site. A draft is not a portfolio piece.
  status: z.literal('published'),
  publishedAt: z.string(),

  /**
   * When the map last recomputed from the catalogue. If this trails the
   * catalogue, the map is the stale side — refresh it before quoting numbers.
   *
   * MUST be a full ISO-8601 timestamp, and a bare date is rejected. TOM found
   * the hole on 2026-08-26: the 41 rows that changed under the 2026 map were
   * updated LATER THE SAME DAY it published, so a date-only mediaAsOf equals
   * publishedAt and a genuine same-day staleness sails straight through. A gate
   * that cannot detect what it advertises is worse than no gate, because it
   * stops anyone looking twice. Day granularity cannot see intra-day drift, so
   * it does not get to claim it can.
   */
  mediaAsOf: z.string().datetime({ offset: true }),

  flightCount: z.number().optional(),

  // Per-map figures, each declaring its own population. Expect BOTH a
  // total-rows count and a plottable count — they legitimately differ, and
  // showing one without saying which it is, is how 344-vs-346 happened.
  stats: z.array(StatSchema).optional(),
});

export const MapPublicationsSnapshotSchema = z.object({
  // When this file was exported from sky_library.
  exportedAt: z.string(),
  publications: z.array(MapPublicationSchema),

  /**
   * Whole-catalogue figures — the scale behind the four published maps.
   *
   * Every one carries its own scope, and the LABELS carry the population too
   * ("media linked to a trip", "flights with exact GPS"), which matters because
   * a stat tile shows the label and hides the scope. On 2026-08-26 an
   * agency-wide figure of 726 was quoted as the media total; the real total is
   * 1,004 and 726 is the subset attached to a trip. It was caught while writing
   * the scope strings — the fourth population error found that day by the act of
   * declaring a population, and the reason a label here must never be a bare
   * noun like "media" or "flights".
   */
  library: z
    .object({
      stats: z.array(StatSchema),
    })
    .optional(),
});

export type MapPublication = z.infer<typeof MapPublicationSchema>;
export type MapPublicationsSnapshot = z.infer<typeof MapPublicationsSnapshotSchema>;

export type SkiesEntry = z.infer<typeof SkiesEntrySchema>;
export type SkiesStat = z.infer<typeof StatSchema>;
export type SkiesEmbed = z.infer<typeof EmbedSchema>;
export type SkiesImage = z.infer<typeof ImageSchema>;
