import { z } from 'zod';

/**
 * Live-Scored Skies — aerial cinematography with original scoring.
 *
 * This is a LINE OF BUSINESS, not a founder's side interest, which is why it
 * gets its own collection at /skies rather than a shelf inside /portfolio
 * ("Design Portfolio" = client websites; filing aerial work there mis-frames it).
 *
 * The thesis of the whole collection is the `map` pairing below: each finished
 * film shown NEXT TO THE FLIGHT PATH THAT PRODUCED IT. Nobody else can show
 * that, because nobody else has the telemetry sitting under the footage. A film
 * with no map still renders — honestly, as a film — but the pairing is the point.
 *
 * Source of truth for the underlying catalogue is TOM's sky_library. This schema
 * is the CONTRACT that data must satisfy to reach the site. It is deliberately
 * NOT a live database read: lastapple.com is statically prerendered and runs on
 * content-as-code, so a row arrives here as MDX committed to git and is validated
 * at build time. A bad row fails `npm run build` instead of reaching a prospect.
 */

// Matches the ImageSchema used by the stream/service/solution collections.
const ImageSchema = z.object({
  src: z.string(),
  alt: z.string(),
  width: z.number().optional(),
  height: z.number().optional(),
});

/**
 * A number shown on the page must carry its own population and an as-of moment.
 *
 * Not pedantry. On 2026-08-02 every gate this site had proved a thing EXISTED
 * rather than that it WORKED, and analytics had been dead for seven months
 * behind green checks. A stat tile with no scope is the same failure shape: it
 * looks true, ages into a lie, and nobody notices.
 *
 * `scope` carries more weight than it first appears. On 2026-08-26 the 2026
 * cross-country map read 344 clips / 201 video / 121.9 GB while the catalogue
 * read 346 / 203 / 122.1, and this was diagnosed as the map being stale. It was
 * not. Two of the 346 rows carry no GPS and are both videos totalling 0.25 GB,
 * so the map — which counts only what it can PLOT — was exactly right, and so
 * was the catalogue, which counts every row. 346 - 2 = 344 reconciles the whole
 * gap. Neither number was wrong and nothing was stale; the population was
 * simply never declared. That is the failure this gate exists to catch.
 *
 * `value` accepts a number as well as a string on purpose: these arrive
 * generated by SQL, and every numeric error in this project's history came from
 * a human retyping a rendered figure. Do not force a cast that invites retyping.
 */
export const StatSchema = z.object({
  label: z.string(),
  value: z.union([z.string(), z.number()]),
  scope: z.string(),
  // Full ISO-8601 timestamp, not a bare date — see MapPublicationSchema.mediaAsOf.
  asOf: z.string().datetime({ offset: true }),
});

/**
 * A published interactive artifact hosted on its own Vercel project — the
 * cross-country trip maps and the Addison 360 sphere.
 *
 * This is the EXTERNAL delivery path. A panorama that ships as image files in
 * this repo does not come through here; it uses `panorama` below, which is the
 * only shape that carries angular extent.
 *
 * These are EMBEDDED, not rebuilt. The live map (dark satellite basemap, points
 * clustered and coloured by the light they were shot in, live filters) is better
 * than anything this repo would draw, and it already ships. Verified 2026-08-25:
 * both apps return 200 and send neither X-Frame-Options nor a CSP
 * frame-ancestors directive, so they are embeddable as-is.
 *
 * `poster` is required because the embed is click-to-load: the still renders,
 * and the iframe is only created when a visitor asks for it. Four live iframes
 * on one page would wreck the phone, and mobile is the stated done-criterion.
 */
export const EmbedSchema = z.object({
  url: z.string().url(),
  poster: ImageSchema,
  // Optional: the sky_library.map_publications slug this embed came from, kept
  // so a snapshot can be reconciled against the catalogue it was exported from.
  publicationSlug: z.string().optional(),
});

/**
 * THE ANGULAR CONTRACT — a panorama this repo hosts and serves itself.
 *
 * Separate from EmbedSchema on purpose. An embed is a URL and a poster; it has
 * no opinion about how much sky the picture actually contains, because the
 * artifact it points at carries its own viewer. A panorama served from
 * public/images is different: THIS repo decides how it is projected, and a
 * projection is a factual claim about the world. Get it wrong and the site
 * shows a prospect a landscape that does not exist.
 *
 * The failure this schema exists to prevent is not hypothetical. The upstream
 * builder (drone-panorama/scripts/build_site.py) was written for a 26-tile full
 * sphere, and when handed a partial sweep it wrote FullPanoWidth ==
 * CroppedAreaWidth with Left 0 / Top 0 and resized a ~4.9:1 image into 2:1 —
 * declaring a partial band to be a complete 360 sphere and stretching it to fit.
 * Flagged by TOM 2026-09-07; the delivered files were hand-tagged instead.
 *
 * So the angles are NOT hand-typed here. They are derived from the GPano crop
 * numbers, which are the authority — TOM's words: the tags "already describe
 * the true crop inside a full sphere, so a GPano-aware viewer places them
 * correctly with no help from you." What a human types below is the six
 * integers that are also embedded in the JPEG, and `measuredHaov`/`measuredVaov`
 * as an independent cross-check. If a typed integer drifts, the derived angles
 * stop matching either the cross-check or the image's own aspect ratio, and the
 * build fails rather than the horizon quietly tilting.
 */
const RenditionSchema = z.object({
  src: z.string(),
  width: z.number().int().positive(),
  height: z.number().int().positive(),
});

/**
 * The GPano crop, exactly as embedded in the delivered JPEG's XMP.
 *
 * Read them back at any time with:
 *   exiftool -XMP-GPano:all public/images/skies/<file>.jpg
 * These six numbers ARE the geometry. Everything the viewer does is arithmetic
 * on them.
 */
const GPanoCropSchema = z.object({
  croppedLeftPixels: z.number().int().nonnegative(),
  croppedTopPixels: z.number().int().nonnegative(),
  croppedWidthPixels: z.number().int().positive(),
  croppedHeightPixels: z.number().int().positive(),
  fullWidthPixels: z.number().int().positive(),
  fullHeightPixels: z.number().int().positive(),
});

export const PanoramaSchema = z
  .object({
    alt: z.string().min(20),

    /**
     * Two renditions, both the FULL band — never a re-crop.
     *
     * `small` is what a phone loads. `large` is capped at 4096px wide for a
     * reason that is not bandwidth: WebGL MAX_TEXTURE_SIZE is 4096 on a large
     * share of mobile GPUs, and a 6788px equirect silently fails to bind on
     * those devices, showing a black frame. The full-width masters stay in the
     * vault and are never shipped to the browser.
     */
    small: RenditionSchema,
    large: RenditionSchema,

    gpano: GPanoCropSchema,

    /**
     * TOM's independently measured extent, in degrees. NOT used to render —
     * it exists solely to disagree with the derived value when something is
     * wrong. Two sources that must agree beat one source that cannot be checked.
     */
    measuredHaov: z.number().positive().max(360),
    measuredVaov: z.number().positive().max(180),
  })
  /**
   * The image's shape must match the sky it claims to cover.
   *
   * An equirectangular crop has pixels-per-degree equal in both axes, so
   * width/height MUST equal haov/vaov. This single check is what makes the
   * upstream defect unshippable: stretching a ~4.9:1 band into 2:1 to fill a
   * viewport breaks this identity immediately, in the build, before a prospect
   * sees a horizon that bends.
   */
  .superRefine((p, ctx) => {
    const haov = (p.gpano.croppedWidthPixels / p.gpano.fullWidthPixels) * 360;
    const vaov = (p.gpano.croppedHeightPixels / p.gpano.fullHeightPixels) * 180;
    const expected = haov / vaov;

    for (const [name, r] of [['small', p.small], ['large', p.large]] as const) {
      const actual = r.width / r.height;
      if (Math.abs(actual - expected) / expected > 0.01) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: [name],
          message:
            `Rendition "${r.src}" is ${r.width}x${r.height} (${actual.toFixed(3)}:1) but the GPano ` +
            `crop describes ${haov.toFixed(1)}deg x ${vaov.toFixed(1)}deg (${expected.toFixed(3)}:1). ` +
            `An equirectangular image cannot be resized to a different aspect than the sky it covers. ` +
            `Fix the file or the tags — do NOT adjust the angles to match a stretched image.`,
        });
      }
    }

    // The derived angles and TOM's measurement must corroborate each other.
    if (Math.abs(haov - p.measuredHaov) > 0.5) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['measuredHaov'],
        message: `GPano crop derives ${haov.toFixed(2)}deg horizontal, but measuredHaov says ${p.measuredHaov}deg. One of them is wrong — ask TOM, do not average them.`,
      });
    }
    if (Math.abs(vaov - p.measuredVaov) > 0.5) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['measuredVaov'],
        message: `GPano crop derives ${vaov.toFixed(2)}deg vertical, but measuredVaov says ${p.measuredVaov}deg. One of them is wrong — ask TOM, do not average them.`,
      });
    }
  });

/**
 * Derive the viewer's parameters from the GPano crop. The ONLY place these
 * numbers are computed; both the page and the viewer read them from here so a
 * caption and a projection can never disagree.
 *
 * vOffset is the angle of the band's centre above the true horizon. Pannellum
 * takes positive = up.
 */
export function panoramaGeometry(p: Panorama) {
  const { croppedTopPixels, croppedHeightPixels, croppedWidthPixels, fullWidthPixels, fullHeightPixels } = p.gpano;
  const haov = (croppedWidthPixels / fullWidthPixels) * 360;
  const vaov = (croppedHeightPixels / fullHeightPixels) * 180;
  // Pixel row of the band's centre, measured down from the zenith, converted to
  // degrees and re-referenced to the equator.
  const centreDegFromZenith = ((croppedTopPixels + croppedHeightPixels / 2) / fullHeightPixels) * 180;
  const vOffset = 90 - centreDegFromZenith;
  return {
    haov,
    vaov,
    vOffset,
    /** True only for a genuine full rotation with both caps present. */
    isFullSphere: haov >= 359.5 && vaov >= 179.5,
  };
}

export const SkiesEntrySchema = z.object({
  title: z.string().min(5),
  description: z.string().max(160),
  slug: z.string(),

  /**
   * Three artifact types share one collection so that publishing the next map
   * or sphere is a content commit rather than a code change.
   *   film — a scored film on the Hank Groman Music channel
   *   map  — a published trip map (flight telemetry)
   *   pano — an interactive aerial panorama
   *
   * A 'pano' is NOT necessarily a sphere, and this comment used to say it was.
   * Corrected 2026-09-07: the Addison piece is a genuine full rotation, but the
   * Tioga piece is a single-band 238.7deg x 48.7deg sweep with no nadir and no
   * zenith. Nothing about "pano" licenses the words 360, sphere, or "look
   * straight up" — only the measured geometry does. A self-hosted panorama
   * carries that geometry in `panorama`, where the build gate can check it.
   */
  kind: z.enum(['film', 'map', 'pano']),

  /**
   * One of the five CREATIVE vectors. Gives the collection its spine and lets
   * /skies group by intent rather than by chronology.
   *
   * DO NOT "reconcile" this list with sky_library.projects.vector. That column
   * has a CHECK constraint on an entirely different vocabulary — trip-story |
   * fcp-mastery | logic-mastery | gear | software | other — which describes the
   * PRODUCTION workstream, not the artistic intent. Two taxonomies wearing the
   * same name (found 2026-08-26). The creative vector rides in that table's
   * meta.creative_vector; read it from there, never from the column.
   *
   * Optional, and left UNSET on purpose until Hank confirms each film's vector.
   * A defensible default guessed by a machine is still a guess, and this label
   * is a claim about what the artist meant.
   */
  vector: z.enum([
    'field-to-frame',
    'drone-psalms',
    'midnight-compositions',
    'composer-in-the-wild',
    'echoes-of-the-journey',
  ]).optional(),

  // ── Film fields ──────────────────────────────────────────────────────────
  // The bare 11-character YouTube id, NOT a URL — the embed is constructed
  // here so every film gets the same click-to-load facade treatment.
  youtubeId: z.string().length(11).optional(),
  // Poster frames are committed to public/images/skies/ rather than hotlinked
  // from i.ytimg.com: no images.remotePatterns is configured, and the flagship
  // page should not put a third-party request on its critical path.
  poster: ImageSchema.optional(),
  durationSec: z.number().optional(),
  // Half of the product name is the scoring. Say which instrument.
  instrument: z.string().optional(),

  // ── Provenance ───────────────────────────────────────────────────────────
  // The trip that PRODUCED this work, as a sky_library trip slug.
  sourceTrip: z.string().optional(),
  locationName: z.string().optional(),
  state: z.string().optional(),
  filmedOn: z.string().optional(),

  /**
   * THE PAIRING — the map of the trip this was scored from.
   *
   * Optional on purpose, and null is the honest value when the map of a film's
   * source trip has not been published yet. Render "map in production"; never
   * pair a film with a map of a different trip to fill the slot.
   */
  map: EmbedSchema.optional(),

  // ── Map / pano entries ───────────────────────────────────────────────────
  // For kind 'map' and 'pano', the artifact itself — when it is hosted as its
  // own external deploy.
  embed: EmbedSchema.optional(),

  /**
   * A panorama served from this repo rather than proxied from its own deploy.
   *
   * The alternative to `embed` for kind 'pano', and the shape that carries
   * angular extent. Use it whenever the image files live in public/images —
   * there is no external viewer to be authoritative, so the geometry has to be
   * declared and gated here.
   */
  panorama: PanoramaSchema.optional(),

  // ── Presentation ─────────────────────────────────────────────────────────
  // Quote stats from the artifact a visitor can click through and check. A
  // number on the page that disagrees with the map it links to is worse than
  // no number at all.
  stats: z.array(StatSchema).optional(),
  releaseDate: z.string(),
  featured: z.boolean().default(false),
  published: z.boolean().default(true),
  order: z.number().default(0),
  body: z.string(),
})
  /**
   * A film without its video is not publishable — it would render as an empty
   * frame in front of a prospect. Fail the build instead.
   */
  .refine(
    (entry) => entry.kind !== 'film' || Boolean(entry.youtubeId),
    { message: 'A film entry requires a youtubeId', path: ['youtubeId'] }
  )
  /**
   * Likewise a map or sphere with nothing to embed. These carry the artifact in
   * `embed`; `map` is reserved for the film-beside-its-flight-path pairing.
   */
  .refine(
    (entry) => entry.kind === 'film' || Boolean(entry.embed) || Boolean(entry.panorama),
    {
      message:
        'A map or pano entry requires either an `embed` (hosted as its own deploy) ' +
        'or a `panorama` (image files served from this repo)',
      path: ['embed'],
    }
  )
  /**
   * One delivery path per entry. Both set means two viewers claiming to be the
   * same artifact, and no way to tell which one the caption describes.
   */
  .refine((entry) => !(entry.embed && entry.panorama), {
    message: 'Set `embed` OR `panorama`, not both — they are two ways to serve one artifact',
    path: ['panorama'],
  });

/**
 * THE BUILD-TIME SNAPSHOT — content/skies/map-publications.json
 *
 * An export of sky_library.map_publications, committed to git and validated
 * here. This is deliberately NOT a runtime database read: lastapple.com is
 * statically prerendered, and a live query would put the flagship page's uptime
 * on Supabase and let a bad row render instead of failing loudly. A commit is
 * the refresh mechanism — which is the Red Light Test the site is built on.
 *
 * `mediaAsOf` is the load-bearing field. The published maps are STATIC
 * SNAPSHOTS: the 2026 cross-country map was published 2026-06-26 and by
 * 2026-08-26 the catalogue underneath it had 41 updated rows, so the map read
 * 201 videos / 121.9 GB while the database read 203 / 122.1. Recording when a
 * map last computed its own numbers is what makes that drift visible instead of
 * silently shipping a page whose stat tiles disagree with the map one click
 * away.
 */
export const MapPublicationSchema = z.object({
  slug: z.string(),
  title: z.string(),
  // The sky_library trip slug this map plots — the join that makes the
  // film-beside-its-flight-path pairing resolve.
  tripSlug: z.string(),
  url: z.string().url(),
  poster: ImageSchema,
  // Only published maps reach the site. A draft is not a portfolio piece.
  status: z.literal('published'),
  publishedAt: z.string(),

  /**
   * When the map last recomputed from the catalogue. If this trails the
   * catalogue, the map is the stale side — refresh it before quoting numbers.
   *
   * MUST be a full ISO-8601 timestamp, and a bare date is rejected. TOM found
   * the hole on 2026-08-26: the 41 rows that changed under the 2026 map were
   * updated LATER THE SAME DAY it published, so a date-only mediaAsOf equals
   * publishedAt and a genuine same-day staleness sails straight through. A gate
   * that cannot detect what it advertises is worse than no gate, because it
   * stops anyone looking twice. Day granularity cannot see intra-day drift, so
   * it does not get to claim it can.
   */
  mediaAsOf: z.string().datetime({ offset: true }),

  flightCount: z.number().optional(),

  // Per-map figures, each declaring its own population. Expect BOTH a
  // total-rows count and a plottable count — they legitimately differ, and
  // showing one without saying which it is, is how 344-vs-346 happened.
  stats: z.array(StatSchema).optional(),
});

export const MapPublicationsSnapshotSchema = z.object({
  // When this file was exported from sky_library.
  exportedAt: z.string(),
  publications: z.array(MapPublicationSchema),

  /**
   * Whole-catalogue figures — the scale behind the four published maps.
   *
   * Every one carries its own scope, and the LABELS carry the population too
   * ("media linked to a trip", "flights with exact GPS"), which matters because
   * a stat tile shows the label and hides the scope. On 2026-08-26 an
   * agency-wide figure of 726 was quoted as the media total; the real total is
   * 1,004 and 726 is the subset attached to a trip. It was caught while writing
   * the scope strings — the fourth population error found that day by the act of
   * declaring a population, and the reason a label here must never be a bare
   * noun like "media" or "flights".
   */
  library: z
    .object({
      stats: z.array(StatSchema),
    })
    .optional(),
});

export type MapPublication = z.infer<typeof MapPublicationSchema>;
export type MapPublicationsSnapshot = z.infer<typeof MapPublicationsSnapshotSchema>;

export type Panorama = z.infer<typeof PanoramaSchema>;
export type SkiesEntry = z.infer<typeof SkiesEntrySchema>;
export type SkiesStat = z.infer<typeof StatSchema>;
export type SkiesEmbed = z.infer<typeof EmbedSchema>;
export type SkiesImage = z.infer<typeof ImageSchema>;
